Implement Angle Interactions
mphowardlab/relentless pull request #282
Opened 2024-12-11 16:50 UTC by clpetix

Implement harmonic, cosine, cosine squared, and spline angles in LAMMPS and HOOMD.

2025-01-07 22:38 UTC, clpetix commented
@mphoward, this should be ready for you to review!

2025-01-08 19:01 UTC, mphoward requested changes
This looks great! I had a couple comments mostly related to class names and inheritance, but otherwise this is almost good to go.

2025-01-08 21:04 UTC, clpetix commented on src/relentless/simulate/lammps.py
> +                    sim[self]["_angles"] = snap.angles
While testing the inheritance, I discovered that in LAMMPS we ran into an issue where if `"exclude":True` for `rdf` without having that type of connection in the snapshot, then it would raise an error because the key was never defined. This addresses that problem.

2025-01-08 21:04 UTC, clpetix commented on src/relentless/simulate/lammps.py
> +                        and sim[sim.initializer]["_bonds"] is not None
This change was also necessary to address the above comment.

2025-01-08 21:10 UTC, clpetix commented on src/relentless/model/potential/potential.py
> +            k.value = 1.0
How would you hand this example given that this is now the base class?

2025-01-08 21:13 UTC, clpetix commented
@mphoward, I added in your suggestions. While testing the inheritance problem pointed out, I found a bug that slipped through the cracks from the bonds PR and addressed that as noted above. 

Aside from a question above, this should be good for you have another look at!

2025-01-08 21:37 UTC, mphoward commented on src/relentless/model/potential/potential.py
> +            k.value = 1.0
The derived classes actually still need a docstring, so you can put specific examples using the right class in each of those. This class should probably get a note saying that it should not be instantiated directly, rather than an example, or else this example should be generic and use "A" as the type.

Small thing to note above: it should be `potential.BondedSpline`

2025-01-08 21:37 UTC, mphoward commented on src/relentless/simulate/lammps.py
> +                    sim[self]["_angles"] = snap.angles
Makes sense! This is an appropriate fix.

2025-01-08 21:37 UTC, mphoward commented on src/relentless/simulate/lammps.py
> +                        and sim[sim.initializer]["_bonds"] is not None
Also agreed.

2025-01-08 21:37 UTC, mphoward commented on src/relentless/model/potential/potential.py
> +class BondedSpline(BondedPotential):
Don't forget to link this into the documentation.

2025-01-08 21:37 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +class AngleSpline(potential.BondedSpline, AnglePotential):
Following with the other comment: here we want to give the class a full docstring describing its constructor and examples. The description of the constructor arguments can be basically copy–pasted from the base class, then add specific examples.

I think you then don't really need the methods below, and can just give an empty class body with `pass` because all of these are just calling the parent methods. The class will inherit the docstrings of those parents, which are probably more detailed.

Same comment applies to the `BondSpline`.

2025-01-08 21:43 UTC, clpetix commented on src/relentless/model/potential/angle.py
> +class AngleSpline(potential.BondedSpline, AnglePotential):
The methods below change the `r` input to `theta`. Thinking more on this the rs are hardcoded in as parameters as "dr-", so this doesn't eliminate all of them. 

If we just pass, are we fine having just using r in all splines?

2025-01-09 01:28 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +class AngleSpline(potential.BondedSpline, AnglePotential):
Oh good point. I think in the base potential tabulator, we use x as a generic coordinate so you could follow the same practice here. I’ll leave it up to you whether you want to just use x for all derived classes, or rename the arguments like you’ve done here.

If you rename the arguments, you can also rename the string name of those parameters by adding a class variable like `_space_coord_name = “x”` in the base class , then override it in the deriving classes to r, theta, etc. You would use this variable to format the parameter names as dr, dtheta, etc.

2025-01-09 17:23 UTC, mphoward approved these changes
Looks great! Please address the small comments here, then this is ready to merge.

2025-01-09 17:23 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +        u(\theta) = \frac{k}{2} (cos(\theta) - cos(\theta_0))^2
```suggestion
        u(\theta) = \frac{k}{2} (\cos \theta - \cos \theta_0)^2
```

2025-01-09 17:23 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +    :math:`k`, respectively.
```suggestion
    from particle *i* to particle *j* and from particle *j* to particle *k*,
    respectively.
```

2025-01-09 17:23 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +        u(\theta) = k (1 + cos(\theta))
```suggestion
        u(\theta) = k (1 + \cos \theta)
```

2025-01-09 17:23 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +    def _derivative(self, param, r, **params):
This should also be `theta`
```suggestion
    def _derivative(self, param, theta, **params):
```
The `derivative` function also needs to have a similar pass-through implementation.

2025-01-09 17:23 UTC, mphoward commented on src/relentless/model/potential/potential.py
> +    _space_coord_name = "x"
I noticed that the parent `BondedPotential` class uses `r` as its space variable for `derivative`. I would go replace that by `x` to make this consistent in our code base.

2025-01-09 20:33 UTC, clpetix commented
@mphoward, I think I've fully sorted out making sure that `r` & `theta` are used appropriately. Let me know if you catch anything else!

2025-01-10 19:48 UTC, mphoward approved these changes
Thanks! I will commit these small edits and merge.

2025-01-10 19:48 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +        r"""Evaluate bond derivative with respect to a variable.
```suggestion
        r"""Evaluate derivative with respect to a variable.
```

2025-01-10 19:48 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +    The angleed spline potential is defined by interpolation through a set of
```suggestion
    The angle spline potential is defined by interpolation through a set of
```

2025-01-10 19:48 UTC, mphoward commented on src/relentless/model/potential/angle.py
> +        r"""Evaluate bond derivative with respect to a variable.
```suggestion
        r"""Evaluate derivative with respect to a variable.
```

2025-01-10 21:12 UTC, merged