Convergence tests for optimizers
mphowardlab/relentless pull request #59
Opened 2021-04-13 14:31 UTC by adisr04

- Add `ConvergenceTest` abstract base class with `GradientTest` and `ValueTest` implementations
- Add `LogicTest` abstract base class with `OrTest` and `AndTest` implementations
- Modify optimizers in `method.py` to use `stop` parameter for convergence criterion
- Document classes in `criteria.py` and add unit tests in `test_criteria.py`

2021-04-13 22:04 UTC, mphoward commented on relentless/optimize/criteria.py
> +    def __init__(self, abs_tol, rel_tol=None, mode='or'):
Overall, I very much like this design, but I think this is a little too base-class heavy. I don't think all `ConvergenceTest`s should be required to support both absolute tolerance and relative tolerance or these different modes.

Rather, I would make `ConvergenceTest` be a light class:
```py
class ConvergenceTest(abc.ABC):
    @abc.abstractmethod
    def converged(self, result):
        pass
```

Then, you can subclass abstract classes for absolute and relative tolerances:
```py
class AbsoluteTolerance(ConvergenceTest):
    def __init__(self, tolerance):
        pass

class RelativeTolerance(ConvergenceTest):
    def __init__(self, tolerance):
        pass
```
and implement specific cases of each:
```py
class GradientAbsoluteTolerance(AbsoluteTolerance):
    pass
class GradientRelativeTolerance(RelativeTolerance):
    pass
```

In this way, `LogicTest` can also subclass from `ConvergenceTest`:
```py
class LogicTest(ConvergenceTest):
    pass
``
I think we voted not to do component-wise and/or tests, so you can remove mode an implement this with the `OrTest` and `AndTest`.

2021-04-18 17:07 UTC, mphoward requested changes
Thanks! This is a great start. I have commented on `criteria.py`. I have a few suggestions for revisions, and also a question about how we are defining the relative-tolerance gradient test. Once you have made these changes, I can review the rest of the PR later.

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +class RelativeGradientTest(RelativeTolerance):
I'm not sure that I actually get what this test is a relative tolerance with respect to. What should we be checking? @zeesherman

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +            elif x.isfree() and np.abs(grad) > tol:
```suggestion
            elif x.isfree() and not self.check(grad,0):
```

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +    def __init__(self, tolerance):
You should an add an argument that is the value you are trying to get to.

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +            if x.value > tol:
```suggestion
            if not self.check(x,self.value):
```

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +        return converged
There should also be a `ValueRelativeTolerance`.

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +            The location of the function at which to check for convergence.
```suggestion
            The result to check for convergence.
```

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +            The location of the function at which to check for convergence.
```suggestion
            The result to check for convergence.
```

2021-04-18 17:07 UTC, mphoward commented on relentless/optimize/criteria.py
> +        return all([t.converged(result) for t in self.tests])
They are just special cases, but people might expect to see `AndTest` and `OrTest`. I think you can add them like this:
```py
class AndTest(AllTest):
    def __init__(self, a, b):
        super().__init__(a,b)
class OrTest(AnyTest):
    def __init__(self, a, b):
        super().__init__(a,b)
```

2021-04-23 22:01 UTC, mphoward requested changes

2021-04-23 22:01 UTC, mphoward commented on relentless/optimize/method.py
>      def rel_tol(self):
You can use a `Tolerance` here now, with `absolute=0`. I would expose `self._tolerance.relative` as `tolerance` for consistency with the gradient test, or else as `relative`.

2021-04-24 02:34 UTC, adisr04 commented on relentless/optimize/criteria.py
> +.. autoclass:: ConvergenceTest
I followed the template you used in `variable.py` and `pair.py` where you put related classes together, not necessarily alphabetically.

2021-04-24 22:06 UTC, mphoward requested changes
I think these changes will fix the issue you were having, and then this will be good to go. I will apply and test them now.

2021-04-24 22:06 UTC, mphoward commented on tests/optimize/test_method.py
> +        print(res_new)
```suggestion
```

2021-04-24 22:08 UTC, mphoward commented on relentless/optimize/criteria.py
> +        """`~relentless._collections.DefaultDict`: The absolute tolerance(s)."""
```suggestion
        """float: The absolute tolerance."""
```

2021-04-24 22:08 UTC, mphoward commented on relentless/optimize/criteria.py
> +        """`~relentless._collections.DefaultDict`: The relative tolerance(s)."""
```suggestion
        """float: The relative tolerance."""
```

2021-04-24 22:22 UTC, mphoward approved these changes

2021-04-24 22:39 UTC, merged